### ISSUE TITLE
图片的复制与粘贴问题

### ISSUE THREAD

**Issue by YubaC** [jrainlau/chat-input-box#3]
复制输入框内的图片再进行粘贴的时候不会粘贴出来一张图片，会粘贴出来一串HTML代码。此外，无法在复制了一个或多个图片文件后进行粘贴。
这个问题经过我的研究，已经有了替代方案，在此挂出以方便后来者：

源代码里压缩图片的目的是为了缩小图片，以方便编辑。但所有的问题也因此而来。

因此，我们不妨将所有压缩图片的代码都去掉，转而用CSS来实现相同的效果，这样不仅能保留图片的分辨率，还能解决上述的几乎所有问题。

只需加入一段css代码：

```css
/* 缩小输入框内的图片，方便编辑 */

.lite-chatinput img {
    max-width: 150px;
    max-height: 150px;
    object-fit: contain;
}
```

其实这里只需设置max-width就足以应对大部分情况了，但是直接从互联网上复制的图片有时候不会等比缩放，故出此下策。
希望有知道原因的大佬解惑。
